import type { BacktestRunSnapshot } from "@intrinsic/contracts";
import { describe, expect, it } from "vitest";
import {
  summarizeInvariants,
  validateRunInvariants,
  type EvidenceEquity,
  type EvidenceTrade,
  type InvariantResult,
  type RunEvidence,
} from "./matrix-invariants";

/**
 * The validators, against a scenario small enough to verify by hand.
 *
 * Four sessions, one security, one contribution, one partial sell. Every number below was computed
 * from the V1 methodology on paper before it was written down, which is the only way a test of a
 * reconciliation is worth anything: a fixture generated by the code it validates would agree with
 * every bug in it.
 *
 * ```text
 * calendar   2026-01-02  2026-01-05  2026-02-02  2026-02-03
 * capital    1,000 initial + 100/month, maximumPositions 2 -> full position = 50% of the portfolio
 *
 * 01-02  close 50   BUY 100%   target 1000 x 0.5 = 500, cash 1000 -> spend 500, 10 shares @ 50
 *                              cash 500, positions 500, total 1,000
 * 01-05  close 60   -          cash 500, positions 600, total 1,100
 * 02-02  close 50   +100 cash  total 1,100 -> target 550, held 500 -> top up 50, +1 share
 *                              cash 550, positions 550, total 1,100, basis unchanged at 50
 * 02-03  close 100  SELL 50%   5.5 shares @ 100 = 550, realized 5.5 x (100 - 50) = 275
 *                              cash 1,100, positions 550, total 1,650
 * ```
 */

const SECURITY_ID = "sec-1";

const SNAPSHOT = {
  securities: [
    {
      securityId: SECURITY_ID,
      symbol: "AAPL",
      name: "Apple Inc.",
      exchangeCode: "NASDAQ",
      currency: "USD",
      buyWindowMode: "FULL",
      buyWindows: [],
    },
  ],
  strategy: {
    definition: {
      buyLevels: [{ id: "b100", percentage: 100 }],
      sellLevels: [{ id: "s50", percentage: 50 }],
      finalExit: null,
    },
  },
} as unknown as BacktestRunSnapshot;

const CALENDAR = ["2026-01-02", "2026-01-05", "2026-02-02", "2026-02-03"];

const TRADES: EvidenceTrade[] = [
  {
    sequence: 1,
    date: "2026-01-02",
    securityId: SECURITY_ID,
    symbol: "AAPL",
    action: "BUY",
    levelId: "b100",
    levelPercentage: 100,
    shares: 10,
    price: 50,
    amount: 500,
    fees: 0,
    realizedPnl: null,
    cashAfter: 500,
    sharesAfter: 10,
    averageCostAfter: 50,
  },
  {
    sequence: 2,
    date: "2026-02-02",
    securityId: SECURITY_ID,
    symbol: "AAPL",
    action: "BUY",
    levelId: "b100",
    levelPercentage: 100,
    shares: 1,
    price: 50,
    amount: 50,
    fees: 0,
    realizedPnl: null,
    cashAfter: 550,
    sharesAfter: 11,
    averageCostAfter: 50,
  },
  {
    sequence: 3,
    date: "2026-02-03",
    securityId: SECURITY_ID,
    symbol: "AAPL",
    action: "SELL",
    levelId: "s50",
    levelPercentage: 50,
    shares: 5.5,
    price: 100,
    amount: 550,
    fees: 0,
    realizedPnl: 275,
    cashAfter: 1100,
    sharesAfter: 5.5,
    averageCostAfter: 50,
  },
];

const EQUITY: EvidenceEquity[] = [
  {
    date: "2026-01-02",
    cash: 500,
    positionsValue: 500,
    totalValue: 1000,
    investedCapital: 1000,
    benchmarkValue: 1000,
    cashBaselineValue: 1000,
    openPositions: 1,
  },
  {
    date: "2026-01-05",
    cash: 500,
    positionsValue: 600,
    totalValue: 1100,
    investedCapital: 1000,
    benchmarkValue: 1100,
    cashBaselineValue: 1000,
    openPositions: 1,
  },
  {
    date: "2026-02-02",
    cash: 550,
    positionsValue: 550,
    totalValue: 1100,
    investedCapital: 1100,
    benchmarkValue: 1000,
    cashBaselineValue: 1100,
    openPositions: 1,
  },
  {
    date: "2026-02-03",
    cash: 1100,
    positionsValue: 550,
    totalValue: 1650,
    investedCapital: 1100,
    benchmarkValue: 1333.33,
    cashBaselineValue: 1100,
    openPositions: 1,
  },
];

function evidence(overrides: Partial<RunEvidence> = {}): RunEvidence {
  return {
    runId: "run-1",
    caseId: "S01-L01-C05",
    status: "COMPLETED",
    failureCode: null,
    failureMessage: null,
    failurePhase: null,
    snapshot: SNAPSHOT,
    startDate: "2026-01-01",
    endDate: "2026-02-03",
    initialCapital: 1000,
    monthlyContribution: 100,
    maximumPositions: 2,
    summary: {
      firstSimulatedDate: "2026-01-02",
      lastSimulatedDate: "2026-02-03",
      tradingDays: 4,
      investedCapital: 1100,
      finalCash: 1100,
      finalPositionsValue: 550,
      finalValue: 1650,
      netProfit: 550,
      realizedPnl: 275,
      unrealizedPnl: 275,
      totalTrades: 3,
      buyTrades: 2,
      sellTrades: 1,
      finalExitTrades: 0,
      winningTrades: 1,
      losingTrades: 0,
      openPositions: 1,
    },
    equity: EQUITY,
    trades: TRADES,
    positions: [
      {
        securityId: SECURITY_ID,
        symbol: "AAPL",
        openedDate: "2026-01-02",
        shares: 5.5,
        averageCost: 50,
        lastPrice: 100,
        marketValue: 550,
        unrealizedPnl: 275,
      },
    ],
    executionCalendarDates: CALENDAR,
    // 10 shares at 100, then 100 more at 90 -> 11.111... shares, 1,333.33 at 120.
    benchmarkCloses: [
      { date: "2026-01-02", close: 100 },
      { date: "2026-01-05", close: 110 },
      { date: "2026-02-02", close: 90 },
      { date: "2026-02-03", close: 120 },
    ],
    firstPriceDateBySecurityId: new Map([[SECURITY_ID, "2020-01-02"]]),
    ...overrides,
  };
}

const byId = (results: readonly InvariantResult[], id: number): InvariantResult =>
  results.find((entry) => entry.id === id) as InvariantResult;

const failed = (results: readonly InvariantResult[]): number[] =>
  results.filter((entry) => entry.status === "FAIL").map((entry) => entry.id);

describe("a correct run", () => {
  const results = validateRunInvariants(evidence());

  it("covers all forty invariants exactly once", () => {
    expect(results).toHaveLength(40);
    expect(new Set(results.map((entry) => entry.id)).size).toBe(40);
    expect(results.map((entry) => entry.id)).toEqual(
      Array.from({ length: 40 }, (_, index) => index + 1),
    );
  });

  it("passes every invariant persisted evidence can settle", () => {
    expect(failed(results)).toEqual([]);
  });

  it("reports the two frame-dependent invariants as needing the archive rather than asserting them", () => {
    // The evaluation frames the day loop consumed are released each calendar year and persisted
    // nowhere. Claiming to have checked them from the database would be a lie in a green report.
    const counts = summarizeInvariants(results);
    expect(counts.needsArchive).toBe(2);
    expect(byId(results, 36).status).toBe("NEEDS_ARCHIVE");
    expect(byId(results, 37).status).toBe("NEEDS_ARCHIVE");
    expect(counts.passed).toBe(38);
  });
});

describe("a run that did not complete", () => {
  const results = validateRunInvariants(
    evidence({
      status: "FAILED",
      failureCode: "PROVIDER_UNAVAILABLE",
      failurePhase: "PREPARING_DATA",
      failureMessage: "No usable data for AAPL",
      summary: null,
      equity: [],
      trades: [],
      positions: [],
    }),
  );

  it("reports the failure once instead of thirty-eight derived failures", () => {
    expect(byId(results, 1).status).toBe("FAIL");
    expect(byId(results, 2).status).toBe("FAIL");
    expect(byId(results, 2).violations?.join(" ")).toContain("PROVIDER_UNAVAILABLE");
    expect(failed(results)).toEqual([1, 2]);
    expect(summarizeInvariants(results).notApplicable).toBe(38);
  });
});

describe("execution dates and the equity curve", () => {
  it("rejects an equity date the pinned calendar does not contain", () => {
    const results = validateRunInvariants(
      evidence({
        equity: [
          ...EQUITY.slice(0, 3),
          { ...(EQUITY[3] as EvidenceEquity), date: "2026-02-04" },
        ],
      }),
    );
    expect(byId(results, 3).status).toBe("FAIL");
  });

  it("rejects duplicate and out-of-order equity dates", () => {
    const duplicated = validateRunInvariants(
      evidence({ equity: [...EQUITY, EQUITY[3] as EvidenceEquity] }),
    );
    expect(byId(duplicated, 4).status).toBe("FAIL");
    const reversed = validateRunInvariants(
      evidence({ equity: [...EQUITY].reverse() }),
    );
    expect(byId(reversed, 5).status).toBe("FAIL");
  });

  it("rejects negative cash", () => {
    const results = validateRunInvariants(
      evidence({
        equity: [{ ...(EQUITY[0] as EvidenceEquity), cash: -1 }, ...EQUITY.slice(1)],
      }),
    );
    expect(byId(results, 6).status).toBe("FAIL");
  });

  it("rejects more open positions than the configuration allows", () => {
    const results = validateRunInvariants(
      evidence({
        maximumPositions: 1,
        equity: EQUITY.map((point) => ({ ...point, openPositions: 2 })),
      }),
    );
    expect(byId(results, 7).status).toBe("FAIL");
  });

  it("rejects an open-position count the trade log does not support", () => {
    const results = validateRunInvariants(
      evidence({ equity: EQUITY.map((point) => ({ ...point, openPositions: 2 })) }),
    );
    expect(byId(results, 8).status).toBe("FAIL");
  });

  it("rejects a broken cash + positions == total identity", () => {
    const results = validateRunInvariants(
      evidence({
        equity: [
          { ...(EQUITY[0] as EvidenceEquity), totalValue: 999 },
          ...EQUITY.slice(1),
        ],
      }),
    );
    expect(byId(results, 9).status).toBe("FAIL");
  });

  it("rejects a simulated date outside the requested period", () => {
    const results = validateRunInvariants(evidence({ endDate: "2026-02-02" }));
    expect(byId(results, 40).status).toBe("FAIL");
  });
});

describe("trades", () => {
  it("rejects an amount that is not shares x price", () => {
    const results = validateRunInvariants(
      evidence({
        trades: [{ ...(TRADES[0] as EvidenceTrade), amount: 499 }, ...TRADES.slice(1)],
      }),
    );
    expect(byId(results, 10).status).toBe("FAIL");
  });

  it("rejects any fee, because V1 methodology is zero fees and zero slippage", () => {
    const results = validateRunInvariants(
      evidence({
        trades: [{ ...(TRADES[0] as EvidenceTrade), fees: 1 }, ...TRADES.slice(1)],
      }),
    );
    expect(byId(results, 10).status).toBe("FAIL");
  });

  it("rejects a BUY outside its security's buy window, and permits an exit outside one", () => {
    const restricted = {
      ...SNAPSHOT,
      securities: [
        {
          ...(SNAPSHOT.securities[0] as BacktestRunSnapshot["securities"][number]),
          buyWindowMode: "CUSTOM" as const,
          buyWindows: [{ startDate: "2026-01-01", endDate: "2026-01-31" }],
        },
      ],
    };
    const results = validateRunInvariants(evidence({ snapshot: restricted }));
    // The 02-02 top-up is now outside the window and must fail; the 02-03 SELL is not restricted.
    expect(byId(results, 11).status).toBe("FAIL");
    expect(byId(results, 12).status).toBe("PASS");
    expect(byId(results, 12).detail).toContain("1 of 1 SELL trades executed outside");
  });

  it("rejects a second BUY for one security on one date", () => {
    const results = validateRunInvariants(
      evidence({
        trades: [
          TRADES[0] as EvidenceTrade,
          { ...(TRADES[1] as EvidenceTrade), date: "2026-01-02", sequence: 2 },
          { ...(TRADES[2] as EvidenceTrade), sequence: 3 },
        ],
      }),
    );
    expect(byId(results, 19).status).toBe("FAIL");
  });

  it("rejects a BUY naming a level the snapshot's definition does not contain", () => {
    const results = validateRunInvariants(
      evidence({
        trades: [{ ...(TRADES[0] as EvidenceTrade), levelId: "ghost" }, ...TRADES.slice(1)],
      }),
    );
    expect(byId(results, 19).status).toBe("FAIL");
  });

  it("rejects a trade before the security's first canonical price", () => {
    const results = validateRunInvariants(
      evidence({
        firstPriceDateBySecurityId: new Map([[SECURITY_ID, "2026-02-01"]]),
      }),
    );
    expect(byId(results, 39).status).toBe("FAIL");
    expect(byId(results, 39).violations?.join(" ")).toContain("before its first canonical price");
  });
});

describe("BUY sizing", () => {
  it("reconciles target, shortfall and available cash", () => {
    expect(byId(validateRunInvariants(evidence()), 18).status).toBe("PASS");
  });

  it("rejects a spend larger than the level's target", () => {
    // 600 spent where the 100% target on a 1,000 portfolio with two slots is 500.
    const results = validateRunInvariants(
      evidence({
        trades: [
          {
            ...(TRADES[0] as EvidenceTrade),
            shares: 12,
            amount: 600,
            cashAfter: 400,
            sharesAfter: 12,
          },
          ...TRADES.slice(1),
        ],
      }),
    );
    expect(byId(results, 18).status).toBe("FAIL");
    expect(byId(results, 18).violations?.join(" ")).toContain("target");
  });

  it("rejects a spend that ignores the level percentage", () => {
    const halfLevel = validateRunInvariants(
      evidence({
        trades: [
          { ...(TRADES[0] as EvidenceTrade), levelPercentage: 50 },
          ...TRADES.slice(1),
        ],
      }),
    );
    expect(byId(halfLevel, 18).status).toBe("FAIL");
  });
});

describe("contributions and the funded scenarios", () => {
  it("derives the schedule from the calendar and matches the cash baseline", () => {
    const results = validateRunInvariants(evidence());
    expect(byId(results, 14).status).toBe("PASS");
    expect(byId(results, 14).detail).toContain("1 deposits");
    expect(byId(results, 15).status).toBe("PASS");
    expect(byId(results, 33).detail).toContain("1100.00");
  });

  it("rejects a deposit on a date that is not its month's first simulated session", () => {
    const results = validateRunInvariants(
      evidence({
        equity: [
          EQUITY[0] as EvidenceEquity,
          { ...(EQUITY[1] as EvidenceEquity), cashBaselineValue: 1100 },
          ...EQUITY.slice(2),
        ],
      }),
    );
    expect(byId(results, 14).status).toBe("FAIL");
  });

  it("rejects a cash baseline that is not initial capital plus contributions to date", () => {
    const results = validateRunInvariants(
      evidence({
        equity: EQUITY.map((point) => ({ ...point, cashBaselineValue: 12345 })),
      }),
    );
    expect(byId(results, 15).status).toBe("FAIL");
  });

  it("reconciles the funded benchmark scenario from accumulated fractional shares", () => {
    expect(byId(validateRunInvariants(evidence()), 17).status).toBe("PASS");
  });

  it("rejects a benchmark valued as a scaled index rather than a funded portfolio", () => {
    // `contributedCapital x (close / openingClose)` — the implementation the funded scenario
    // replaced. It agrees only for a run with no contributions, which is exactly why it is checked.
    const scaled = 1100 * (120 / 100);
    const results = validateRunInvariants(
      evidence({
        equity: [
          ...EQUITY.slice(0, 3),
          { ...(EQUITY[3] as EvidenceEquity), benchmarkValue: scaled },
        ],
      }),
    );
    expect(byId(results, 17).status).toBe("FAIL");
  });

  it("treats a run with no absolute benchmark values as not applicable rather than passing", () => {
    const results = validateRunInvariants(
      evidence({
        equity: EQUITY.map((point) => ({ ...point, benchmarkValue: null })),
      }),
    );
    expect(byId(results, 16).status).toBe("NOT_APPLICABLE");
    expect(byId(results, 17).status).toBe("NOT_APPLICABLE");
  });
});

describe("position lifecycle rules", () => {
  it("permits a level to re-fire on a contribution date and rejects it on any other", () => {
    expect(byId(validateRunInvariants(evidence()), 20).status).toBe("PASS");
    expect(byId(validateRunInvariants(evidence()), 21).detail).toContain("1 top-up");

    const onOrdinaryDay = validateRunInvariants(
      evidence({
        trades: [
          TRADES[0] as EvidenceTrade,
          { ...(TRADES[1] as EvidenceTrade), date: "2026-01-05" },
          TRADES[2] as EvidenceTrade,
        ],
      }),
    );
    expect(byId(onOrdinaryDay, 20).status).toBe("FAIL");
    expect(byId(onOrdinaryDay, 21).status).toBe("FAIL");
    expect(byId(onOrdinaryDay, 22).status).toBe("FAIL");
    expect(byId(onOrdinaryDay, 22).violations?.join(" ")).toContain("rebalance");
  });

  it("rejects a top-up in a configuration that contributes nothing", () => {
    const results = validateRunInvariants(evidence({ monthlyContribution: 0 }));
    expect(byId(results, 21).status).toBe("FAIL");
  });

  it("rejects a smaller tier trading after a larger one has settled", () => {
    const results = validateRunInvariants(
      evidence({
        trades: [
          TRADES[0] as EvidenceTrade,
          {
            ...(TRADES[1] as EvidenceTrade),
            date: "2026-01-05",
            levelId: "b25",
            levelPercentage: 25,
          },
          TRADES[2] as EvidenceTrade,
        ],
      }),
    );
    expect(byId(results, 20).status).toBe("FAIL");
    expect(byId(results, 20).violations?.join(" ")).toContain("settles every smaller one");
  });

  it("rejects a SELL that is not the level's percentage of the remaining shares", () => {
    const results = validateRunInvariants(
      evidence({
        trades: [
          ...TRADES.slice(0, 2),
          { ...(TRADES[2] as EvidenceTrade), shares: 3, sharesAfter: 8 },
        ],
      }),
    );
    expect(byId(results, 23).status).toBe("FAIL");
  });

  it("rejects a SELL level firing twice in one lifecycle", () => {
    const results = validateRunInvariants(
      evidence({
        trades: [
          ...TRADES,
          {
            ...(TRADES[2] as EvidenceTrade),
            sequence: 4,
            shares: 2.75,
            amount: 275,
            sharesAfter: 2.75,
            cashAfter: 1375,
            realizedPnl: 137.5,
          },
        ],
      }),
    );
    expect(byId(results, 24).status).toBe("FAIL");
  });

  it("rejects a FINAL EXIT that leaves shares open, and a same-date re-entry after one", () => {
    const closing: EvidenceTrade = {
      ...(TRADES[2] as EvidenceTrade),
      action: "FINAL_EXIT",
      levelId: "exit",
      levelPercentage: null,
      shares: 11,
      amount: 1100,
      sharesAfter: 0,
      averageCostAfter: null,
      realizedPnl: 550,
      cashAfter: 1650,
    };
    expect(
      byId(
        validateRunInvariants(
          evidence({
            trades: [...TRADES.slice(0, 2), { ...closing, sharesAfter: 1 }],
          }),
        ),
        25,
      ).status,
    ).toBe("FAIL");

    const reentered = validateRunInvariants(
      evidence({
        trades: [
          ...TRADES.slice(0, 2),
          closing,
          {
            ...(TRADES[0] as EvidenceTrade),
            sequence: 4,
            date: "2026-02-03",
            price: 100,
            shares: 8.25,
            amount: 825,
            cashAfter: 825,
            sharesAfter: 8.25,
            averageCostAfter: 100,
          },
        ],
      }),
    );
    expect(byId(reentered, 26).status).toBe("FAIL");
  });
});

describe("cost basis and profit and loss", () => {
  it("rejects an average cost a BUY did not produce", () => {
    const results = validateRunInvariants(
      evidence({
        trades: [
          { ...(TRADES[0] as EvidenceTrade), averageCostAfter: 45 },
          ...TRADES.slice(1),
        ],
      }),
    );
    expect(byId(results, 28).status).toBe("FAIL");
  });

  it("rejects a partial SELL that moved the basis per share", () => {
    // AVERAGE_COST reduces shares and cost proportionally, so `Gain` keeps describing the same
    // position. A moved basis is a different cost policy wearing the same name.
    const results = validateRunInvariants(
      evidence({
        trades: [...TRADES.slice(0, 2), { ...(TRADES[2] as EvidenceTrade), averageCostAfter: 62 }],
      }),
    );
    expect(byId(results, 28).status).toBe("FAIL");
  });

  it("rejects realized P&L that is not shares x (price - basis)", () => {
    const results = validateRunInvariants(
      evidence({
        trades: [...TRADES.slice(0, 2), { ...(TRADES[2] as EvidenceTrade), realizedPnl: 300 }],
      }),
    );
    expect(byId(results, 29).status).toBe("FAIL");
  });

  it("rejects a summary that does not sum its own trades", () => {
    const results = validateRunInvariants(
      evidence({
        summary: {
          ...(evidence().summary as NonNullable<RunEvidence["summary"]>),
          realizedPnl: 999,
        },
      }),
    );
    expect(byId(results, 29).status).toBe("FAIL");
  });

  it("rejects unrealized P&L and market value that do not follow from the position", () => {
    const results = validateRunInvariants(
      evidence({
        positions: [
          {
            ...(evidence().positions[0] as RunEvidence["positions"][number]),
            unrealizedPnl: 10,
            marketValue: 1,
          },
        ],
      }),
    );
    expect(byId(results, 30).status).toBe("FAIL");
    expect(byId(results, 31).status).toBe("FAIL");
  });
});

describe("summary reconciliation", () => {
  it("rejects a final value that is not the last equity row", () => {
    const results = validateRunInvariants(
      evidence({
        summary: {
          ...(evidence().summary as NonNullable<RunEvidence["summary"]>),
          finalValue: 1651,
        },
      }),
    );
    expect(byId(results, 32).status).toBe("FAIL");
  });

  it("rejects trade counts that disagree with the persisted trades", () => {
    const results = validateRunInvariants(
      evidence({
        summary: {
          ...(evidence().summary as NonNullable<RunEvidence["summary"]>),
          totalTrades: 2,
          winningTrades: 0,
        },
      }),
    );
    expect(byId(results, 34).status).toBe("FAIL");
    expect(byId(results, 34).violations?.length).toBe(2);
  });

  it("rejects a position count that disagrees with the persisted positions", () => {
    const results = validateRunInvariants(
      evidence({
        summary: {
          ...(evidence().summary as NonNullable<RunEvidence["summary"]>),
          openPositions: 3,
        },
      }),
    );
    expect(byId(results, 35).status).toBe("FAIL");
  });

  it("rejects an invested capital that is not the funding schedule", () => {
    const results = validateRunInvariants(
      evidence({
        summary: {
          ...(evidence().summary as NonNullable<RunEvidence["summary"]>),
          investedCapital: 1000,
        },
      }),
    );
    expect(byId(results, 33).status).toBe("FAIL");
  });
});

describe("a run that legitimately never traded", () => {
  it("is not a failure", () => {
    // `S06` is a deliberately sparse confluence strategy and `C03`/`C04` are short periods. A run
    // with nothing to do must report green, or the matrix trains its reader to ignore red.
    const results = validateRunInvariants(
      evidence({
        monthlyContribution: 0,
        trades: [],
        positions: [],
        equity: CALENDAR.map((date) => ({
          date,
          cash: 1000,
          positionsValue: 0,
          totalValue: 1000,
          investedCapital: 1000,
          benchmarkValue: null,
          cashBaselineValue: 1000,
          openPositions: 0,
        })),
        summary: {
          firstSimulatedDate: "2026-01-02",
          lastSimulatedDate: "2026-02-03",
          tradingDays: 4,
          investedCapital: 1000,
          finalCash: 1000,
          finalPositionsValue: 0,
          finalValue: 1000,
          netProfit: 0,
          realizedPnl: 0,
          unrealizedPnl: 0,
          totalTrades: 0,
          buyTrades: 0,
          sellTrades: 0,
          finalExitTrades: 0,
          winningTrades: 0,
          losingTrades: 0,
          openPositions: 0,
        },
      }),
    );
    expect(failed(results)).toEqual([]);
  });
});

describe("tolerances at the contract's maximum capital", () => {
  /**
   * `C08` starts with a billion dollars, so a 1997 position in a stock trading at sixteen cents
   * split-adjusted holds 273 million shares — where 5e-9 of rounding in an eight-decimal basis is
   * $1.37 of profit and loss. The tolerance has to follow the share count, or a correct run is
   * reported as a defect; it must not follow it so far that a real disagreement disappears.
   */
  const SHARES = 273_561_496.4795988;
  const PRICE = 0.1596;
  const BASIS = 0.19265445;

  const hugePosition = (realizedPnl: number): RunEvidence =>
    evidence({
      monthlyContribution: 0,
      initialCapital: 1_000_000_000,
      trades: [
        {
          sequence: 1,
          date: "2026-01-02",
          securityId: SECURITY_ID,
          symbol: "AAPL",
          action: "BUY",
          levelId: "b100",
          levelPercentage: 100,
          shares: SHARES,
          price: BASIS,
          amount: Number((SHARES * BASIS).toFixed(2)),
          fees: 0,
          realizedPnl: null,
          cashAfter: 0,
          sharesAfter: SHARES,
          averageCostAfter: BASIS,
        },
        {
          sequence: 2,
          date: "2026-02-03",
          securityId: SECURITY_ID,
          symbol: "AAPL",
          action: "FINAL_EXIT",
          levelId: "exit",
          levelPercentage: null,
          shares: SHARES,
          price: PRICE,
          amount: Number((SHARES * PRICE).toFixed(2)),
          fees: 0,
          realizedPnl,
          cashAfter: Number((SHARES * PRICE).toFixed(2)),
          sharesAfter: 0,
          averageCostAfter: null,
        },
      ],
      positions: [],
      equity: EQUITY.map((point) => ({ ...point, cashBaselineValue: 1_000_000_000, investedCapital: 1_000_000_000 })),
      summary: null,
    });

  const exact = SHARES * (PRICE - BASIS);

  it("accepts a difference that is only the eight-decimal basis being rounded", () => {
    // The engine multiplied unrounded floats; this reconstruction multiplies the stored basis.
    const results = validateRunInvariants(hugePosition(Number((exact + 0.97).toFixed(2))));
    expect(byId(results, 29).status).toBe("PASS");
    expect(byId(results, 10).status).toBe("PASS");
  });

  it("still rejects a difference the representation cannot explain", () => {
    const results = validateRunInvariants(hugePosition(Number((exact + 500).toFixed(2))));
    expect(byId(results, 29).status).toBe("FAIL");
  });

  it("keeps a cent-scale disagreement visible on an ordinary-sized position", () => {
    // Ten shares buy no slack at all: the budget follows the share count, so it stays tight here.
    const results = validateRunInvariants(
      evidence({
        trades: [
          ...TRADES.slice(0, 2),
          { ...(TRADES[2] as EvidenceTrade), realizedPnl: 276 },
        ],
      }),
    );
    expect(byId(results, 29).status).toBe("FAIL");
  });
});
